apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cd1-agent

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment-cost.yaml
  - deployment-hdsp.yaml
  - deployment-bdp.yaml
  - deployment-drift.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: cd1-agent
  app.kubernetes.io/managed-by: kustomize
